# Generated by Django 5.2 on 2025-04-14 21:23

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_coupon_order_discount_amount_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[shop.models.validate_image_file_extension]),
        ),
    ]
